{{- $servicelist := .Values.services }}
{{- range $service := $servicelist }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}-service
spec:
  selector:
    app: {{ $service.name }}
  ports:
    - protocol: TCP
      port: {{ $service.port }}
      targetPort: {{ $service.port }}
      nodePort: {{ $service.nport }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
